# Generated by Django 2.2.2 on 2019-07-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('customer', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=50)),
                ('user_name', models.CharField(default='Grasp Chemicals', max_length=25)),
                ('date_created', models.DateTimeField(verbose_name='date_published')),
                ('vat_as_per_invoice', models.DecimalField(decimal_places=2, default=0.15, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('date_created', models.DateTimeField(verbose_name='date_published')),
                ('user_name', models.CharField(default='Grasp Chemicals', max_length=25)),
                ('order_number', models.CharField(default='0000000', max_length=25)),
                ('vat_number', models.CharField(default='00000', max_length=25)),
                ('vat', models.DecimalField(decimal_places=2, default=0.15, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('customer', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=50)),
                ('user_name', models.CharField(default='Grasp Chemicals', max_length=25)),
                ('date_created', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.CreateModel(
            name='IProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('p_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ICustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_address', models.CharField(max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='IBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('accout_num', models.CharField(max_length=25)),
                ('account_type', models.CharField(max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='DProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('p_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='CProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('p_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Quotation')),
            ],
        ),
    ]
