# Generated by Django 2.2.2 on 2019-07-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('p_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
            ],
        ),
    ]
