# Generated by Django 2.2.2 on 2019-07-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='c_address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='c_name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
