# Generated by Django 2.2.2 on 2019-06-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190616_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_address', models.CharField(max_length=100)),
                ('c_person', models.CharField(max_length=50)),
                ('c_mobile_n', models.CharField(max_length=50)),
                ('c_tel', models.CharField(max_length=50)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Invoice')),
            ],
        ),
    ]
