# Generated by Django 2.2.2 on 2019-06-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_icustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='IBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('accout_num', models.CharField(max_length=25)),
                ('swift_code', models.CharField(max_length=50)),
                ('sort_code', models.IntegerField()),
                ('account_type', models.CharField(max_length=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Invoice')),
            ],
        ),
    ]
