# Generated by Django 2.2.2 on 2019-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_ibankdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
    ]
