# Generated by Django 2.2.2 on 2019-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190616_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user_name',
            field=models.CharField(default='Engine', max_length=25),
        ),
    ]
