# Generated by Django 2.2.2 on 2019-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_invoice_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user_name',
            field=models.CharField(default='Grasp Chemicals', max_length=25),
        ),
    ]
