# Generated by Django 2.2.2 on 2019-06-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190616_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(default='0000000', max_length=25),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_number',
            field=models.CharField(default='00000', max_length=25),
        ),
    ]
