# Generated by Django 2.2.2 on 2019-06-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20190616_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icustomer',
            name='c_mobile_n',
        ),
        migrations.RemoveField(
            model_name='icustomer',
            name='c_person',
        ),
        migrations.RemoveField(
            model_name='icustomer',
            name='c_tel',
        ),
    ]
