# Generated by Django 2.2.2 on 2019-06-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20190617_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('customer', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=50)),
                ('user_name', models.CharField(default='Grasp Chemicals', max_length=25)),
                ('date_created', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
        migrations.RemoveField(
            model_name='ibankdetail',
            name='sort_code',
        ),
        migrations.RemoveField(
            model_name='ibankdetail',
            name='swift_code',
        ),
        migrations.RemoveField(
            model_name='iproduct',
            name='p_code',
        ),
        migrations.CreateModel(
            name='CProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('p_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Quotation')),
            ],
        ),
    ]
