# Generated by Django 2.2.2 on 2019-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20190617_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='icustomer',
            name='c_vat',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
