# Generated by Django 2.2.2 on 2019-06-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_icustomer_c_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icustomer',
            name='c_vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
