# Generated by Django 2.2.2 on 2019-06-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20190619_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icustomer',
            name='c_vat',
        ),
    ]
