# Generated by Django 2.2.2 on 2019-06-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_icustomer_c_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icustomer',
            name='c_vat',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
