# Generated by Django 2.2.2 on 2019-06-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('p_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Delivery')),
            ],
        ),
    ]
