# Generated by Django 2.2.2 on 2019-06-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_dproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='vat_as_per_invoice',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=2),
        ),
    ]
